# pulseaudio
solution to pa_context_connect() failed: Connection refused
